### ISSUE TITLE
Estrutura

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/startup-mission-base-rails#1]
# Criar toda estrutura que um projeto real
## Release v0.1
- [x] Tailwind
   - [x] Flowbite
- [x] Goal
   - [x] #21
   - [x] #23
   - [x] #24
   - [x] #16
   - [x] #26
- [x] #10
- [x] #41
   - [ ] Stripe, https://stripe.com/docs/payments e https://github.com/stripe-samples/checkout-foundations-ruby
- [x] #40
   - [x] Client
   - [ ] #46
     - [ ] Permissão
- [x] Active Admin 
   - [x] #27
   - [x] Goal
   - [x] #9
- [x] API
   - [x] #32
   - [x] Documentação
- [x] Mailer
   - [x] #19
- [x] Job
   - [x] #20
- [x] Test
   - [x] Model
   - [x] Controller
   - [x] Feature, não conseguir fazer funcionar no docker
   - [x] Business
   - [x] API
- [x] Gem
   - [x] #7
   - [x] #8
   - [x] #36
- [x] I18n
  - [x] #2
  - [x] #12
  - [x] #15
- [x] #4
   - [x] Rubycritic
   - [x] Rubocop
   - [x] #5
   - [x] Selenium, não conseguir fazer funcionar no docker
- [x] Docker
- [x] Readme
- [ ] Identidade
  - [x] #47
## Release v0.2
- [ ] Flowbit
   - [ ] Alerta, https://flowbite.com/docs/components/alerts/
   - [ ] Dashboard e Report, https://free-demo.tailadmin.com/
- [ ] Indicadores
   - [ ] #34
   - [ ] #35
- [ ] SimpleForm
   - [ ] Customizar para suportar tailwind e flowbite no initialize
## Release v0.3
- [ ] Hotwired
   - [ ] Turbo Frame
   - [ ] Turbo Stream
   - [ ] Stimulus
